#!/usr/bin/env bash
set -e
if [ $# -ne 1 ]; then
    echo "Error: expected one argument: URL of data file"
    exit 1
fi
rm -rf fetched_data
mkdir -p fetched_data
pushd fetched_data
wget -O ONSData.zip $1
unzip ONSData.zip
pushd Data
datafile=$(find . -maxdepth 1 -name '*.csv')
popd
popd
cargo run -- fetched_data/Data/$datafile postcodes.pack
terser nearmypostcode.js -o nearmypostcode.min.js --source-map
./build_module
./test.js
zip nearmypostcode.zip postcodes.pack nearmypostcode.js nearmypostcode.min.js nearmypostcode.min.js.map nearmypostcode.mjs
